#configuramos el confi server y la ruta en donde encontrará toda la configuracion de todos nuestros microservicios se llamará así "classpath:/configurations"
server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations