#en cloud le decimos que el gateway estara activo, este micros. estará pendiente y redireccionará a los diferentes microservicios
#** es un predicated, aca le decimos que puede acceder a las otras rutas que tengan api/
#para que no se registre en el servidor de eureka, ya que no es necesario
eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/api/student/**
          - id: courses
            uri: http://localhost:9090
            predicates:
              - Path=/api/course/**